# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8Ve1GMPuhSjD1FEcnKaaTLiCw2fmtVp
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("/content/archive (2).zip")

print(df.shape)

df.info()

df.describe()

df.isnull().sum()

df.replace(" ?", np.nan, inplace=True)

df.dropna(inplace=True)

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == object:
        df[col] = encoder.fit_transform(df[col])

X = df.drop("income", axis=1)

y = df["income"]

print(df.columns)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

print(cm)